logging:
  level:
    sql: debug

server:
  port: 8081
  servlet:
    context-path: /quartett

spring:
  profiles:
    active: profile_develop
  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:8082/vehicle
    username: develop
    password: secret
  jpa:
    database:
      POSTGRESQL
    open-in-view: true # disable a warning
    generate-ddl: false
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none # update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        #        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:liquibase/changelog.xml
    enabled: true
    default-schema: public

keycloak:
  realm: angular
  auth-server-url: http://192.168.0.5:81
  ssl-required: external
  resource: angular-example
  public-client: true
  credentials:
    secret: Mgi5qHbo37DQnAbefXLMJGK1R0ppUeYf
  use-resource-role-mappings: false   # when false: use realm-roles
  bearer-only: true
