logging:
  level:
    sql: debug

server:
  port: 8081
  servlet:
    context-path: /quartett

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:8082/vehicle
    username: develop
    password: secret
  jpa:
    database:
      POSTGRESQL
    open-in-view: true # disable a warning
    generate-ddl: false
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
#        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false


#graphql:
#  servlet:
#    websocket:
#      enabled: false
